name: Docker Build & Publish

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io --username mikbot --password "$GITHUB_TOKEN"
      - name: Push Image
        run: |
          docker buildx build \
                  --tag  ghcr.io/traewelldroid/auth-service/service:"$GITHUB_SHA" \
                  --tag  ghcr.io/traewelldroid/auth-service/service:latest \
                  --file ./Dockerfile \
                  --output type=image,push=true .
